# from https://raw.githubusercontent.com/tidyverse/dplyr/master/.github/workflows/pkgdown.yaml
on:
  push:
    branches: main

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          devtools::install_deps(dependencies = TRUE)

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
